import {
  DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH,
} from '../src/lib/content/todayRealFeedEvidenceStarter';
import {
  DEFAULT_TODAY_REAL_FEED_REPORT_OUTPUT_PATH,
} from '../src/lib/content/todayRealFeedPilotReport';

const lines = [
  'SignalDesk Today real-feed local operator help',
  '',
  'Phases:',
  '1. Baseline mock confirmation',
  '   - Run npm run phase4:today-pilot-check and confirm mode: mock_default when VITE_USE_REAL_CONTENT_FEED=false.',
  '2. Real-feed env confirmation',
  '   - Set VITE_USE_REAL_CONTENT_FEED=true plus VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY, then rerun phase4:today-pilot-check.',
  '3. Today real-card render check',
  '   - Run npm run dev, open Today, and confirm real cards render with the existing style.',
  '4. Detail page safety check',
  '   - Open one real card and confirm Detail opens safely.',
  '5. Source/provenance check',
  '   - Confirm source provenance or source links are visible when available.',
  '6. Enrichment behavior check',
  '   - Confirm completed non-empty enriched text wins and incomplete or blank enrichment falls back safely.',
  '7. Filter behavior check',
  '   - Confirm AI/OpenAI filter matches expected cards and nonmatching filters show the normal filter-empty state.',
  '8. real_empty check',
  '   - If available, capture a genuine real_empty state distinct from filter_empty.',
  '9. Mobile quality check',
  '   - Confirm the real-feed Today view remains acceptable on a mobile-sized viewport.',
  '10. Freshness check',
  '   - Confirm publish dates or recency signals still look acceptable.',
  '11. Source coverage check',
  '   - Confirm the real cards are coming from a reasonable source mix.',
  '12. Rollback-to-mock check',
  '   - Set VITE_USE_REAL_CONTENT_FEED=false, restart or rebuild/redeploy, and confirm Today returns to mock.',
  '13. Evidence update commands',
  '   - If you already have docs/evidence/today-real-feed-pilot-evidence.local.json, start with review, not create.',
  '   - Use presets or explicit updater flags to record one missing bucket at a time.',
  '14. Evidence review command',
  '   - Run npm run phase4:today-evidence-review -- docs/evidence/today-real-feed-pilot-evidence.local.json.',
  '   - If review stays continue_pilot, run npm run phase4:today-evidence-next -- docs/evidence/today-real-feed-pilot-evidence.local.json.',
  '15. Sanitized report command',
  `   - Run npm run phase4:today-pilot-report -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH} --out ${DEFAULT_TODAY_REAL_FEED_REPORT_OUTPUT_PATH}.`,
  '',
  'Commands:',
  '- npm run phase4:create-today-evidence',
  '- npm run phase4:today-pilot-check',
  `- npm run phase4:update-today-evidence -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH} --preset real-cards-rendered`,
  `- npm run phase4:today-evidence-review -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH}`,
  `- npm run phase4:today-evidence-next -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH}`,
  `- npm run phase4:today-evidence-status -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH}`,
  `- npm run phase4:today-pilot-report -- ${DEFAULT_TODAY_REAL_FEED_EVIDENCE_OUTPUT_PATH} --out ${DEFAULT_TODAY_REAL_FEED_REPORT_OUTPUT_PATH}`,
  '',
  'Rollback reminder:',
  '- Set VITE_USE_REAL_CONTENT_FEED=false, then restart or rebuild/redeploy and confirm Today returns to mock.',
  '',
  'Boundaries:',
  '- Local-only helper flow.',
  '- No Supabase call unless the app is running separately during manual QA.',
  '- No AI call.',
  '- No content write.',
  '- No secret values printed.',
  '- Do not commit local evidence or local pilot reports.',
];

process.stdout.write(`${lines.join('\n')}\n`);
